import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const defer=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)}};
function generate(file,start,end,env){const text=readFileSync(new URL('../src/'+file,import.meta.url),'utf8'),offset=text.indexOf(start);const source=text.slice(text.indexOf('  const generate = async () => {',offset),text.indexOf(end,offset));const compiled=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;return new Function(...Object.keys(env),compiled+';return generate;')(...Object.values(env));}
const tick=()=>new Promise(r=>setImmediate(r));
test('背景生成等待草稿保存时关闭面板，迟到保存不发音频请求',async()=>{const wait=defer(),sent=[],active={current:true};const env={state:{settings:{routeBlocked:false},jobs:[]},resumeRoute:false,localRecoveryPending:false,needsPresenceTemplate:false,presenceTemplateWarning:'',setError(){},setNotice(){},setFeedbackScope(){},setPending(){},setResumeRoute(){},unknown:false,retryUnknown:false,chapter:{id:'chapter',revision:1},unit:{id:'unit',members:['one']},mode:'scene',active,withSavedDrafts:async(_scope,_dependencies,next)=>next(),dependencies:()=>[],controller:{flush:()=>wait.promise},events:[],unitHasDraft:()=>false,draftScopeRevision:(_scope,base)=>base,confirmed:{current:{chapterRevision:1,revision:1}},confirmedEvents:{current:new Map()},outstandingAttemptIds:[],grantId:'grant',submitOperation:async(...args)=>{sent.push(args);return {};},setRetryUnknown(){},refresh:async()=>{}};const pending=generate('UnitPanel.tsx','function UnitDetails','  const openEvent',env)();await tick();active.current=false;wait.resolve();await pending;assert.equal(sent.length,0);});
test('声音候选等待描述保存时关闭，迟到回执不发模型请求',async()=>{const wait=defer(),sent=[],active={current:true};const env={routeBlocked:false,resumeRoute:false,setError(){},setPending(){},setResumeRoute(){},draft:{flush:()=>wait.promise},session:{id:'session'},savedSession:{current:null},active,actualProject:'project',actualChapter:undefined,target:undefined,grantId:'grant',unknown:false,retryUnknown:false,jobs:[],submitOperation:async(...args)=>{sent.push(args);return {};},setRetryUnknown(){},refresh:async()=>{}};const pending=generate('VoiceCreation.tsx','export default function','  return <>',env)();await tick();active.current=false;wait.resolve({revision:1,dirty:false});await pending;assert.equal(sent.length,0);});
